{{- if .Values.authEnabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ongdb.secrets.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "ongdb.name" . }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
type: Opaque
data:
  {{- if .Values.ongdbPassword }}
  ongdb-password: {{ .Values.ongdbPassword | b64enc | quote }}
  {{- else }}
  ongdb-password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
{{- end -}}
